language: node_js
node_js:
- '8'
install:
- npm i -g metricly-cli
script:
- metricly package validate && metricly package lint
notifications:
  slack:
    secure: 1rY1Eu5HvRH40ymUGnJTgDBC+mvzoNRygC+Ce9ntDjKpKUdIMnDjhOXkKl1lFahoC2mqeY6YLksE0GSLjQK/bkFfabf2/tWSyJN23BvmqMEeoY6qvxQMUMkoFj77vh2ur27iZCyFJVdPjns9hw+nwvgFplWpgQ1vE08V+IbW6L8IV1MNAy53XPacfAIo/KCuZsqvotL4YafGx86OyjEHBgNHI/rt8MH7CrvQkdFnxsBOhNHqeEGXIH/Pbf6Bu1on1l1PwT4fvGmiR/mHhaeapa1P8SlIMt0W1uXkiU0z4Kdivv1Q4fq7m26IJIEHY4AeR6mVeF5vZf0dPHHCWmYM0Id3ExUuw5Mqb+JyC3ii5dPhMoYUiwjlZQJ7Ay/7qhTzVSTw6bHeKOrFhJXSF3LSZZvHgqAAT3AYXyPX4xei2Qe8bMk/S2EK3VZNIcxa/TV1vZN1OngZTXXBxp0u3y9Ts3hXRfA/2G5D/GTGyVQooLmmjq9t6Tff0DYSmiTj6VbXp5jiuiH6lJEJjyF5WyPjG485mQ29HCpRZeudbFs/nsIPndpSK3d7T5XqQY+DJDWZl+8R4lijk84tsEP/D/PgOmD1E04EwvAAOTp/cGMrmvcoOQlWmzlfO+lc5ClbpxyouGV53sgDN1X1CAzokt6brTUVtTySAfPxz8ryX3Pzjn0=
