language: node_js
node_js:
- '6'
script:
- npm i git+https://git@github.com/Netuitive/netuitive-package-validator.git; node
  -e "require('package-validator').validate('.', require('./package.json').id)";
notifications:
  slack:
    secure: Qm3TiP1Kpuo8nna93JCwAfEZ+4uTLqiz6vIL9u+pOAtevuKHQ7r3IxjJSSCwmDC/w0d+tOBOjgAJnZ5rfpV2/uTgF65jgChXgEY7BDHU5CZI7qeVcfSJZUf+ce2BerA2lkKpaY1im8U3Mb6a0rirypsJWTiquw/S7HDNJG00vrMpPGq8wi91Ucq7xhMJLG+vCkl1GkZ10NCFmQSjWsk8uvcazdJGjLTRvccVS3UoSP2dXY53fBFo7d94QIKY0GAsdlZzOX1fc/4CvWYRlRnyDQtpL3MMYpY1voecEB00KKG3ZHIRB2aLj2RRNEF3lR6eB1fxD4TxRyeXBJQ7M51/CKF/IFOB2xzrRR8cpkLuiGsfw/bMByakBvWgiLG66kkGKc/ShnScdFTVCrHwlRxJXPnOV8lG9K7rBMV/Asx7S/OCOY3p+IBQf599nBzO9qXE1dlIQVBkT9EYi2/axr94DrH4QtdcUbInru0xrS7XQIl0Ie7fuQn65aU5CYJJM4278BctIxk35apBXMJG6i2Tpr9WWinFj0SnZcC4WSf07Kz3xwCY0gqTOoq9Tt51o3yBh3T8B1f1LEjmU26D5ADZmiu7fis5104KOjRCO26+Agyk3hye8GVyK6rSloRxHKx1sycCf9gdJdxwhzFgEVbKF8l+11GD0BE4/PbIGCjEz8w=
